name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  precommit:
    uses: ./.github/workflows/lintint_reusable.yml

  backend-go:
    uses: ./.github/workflows/backend_go_reusable.yml

  hopp-core:
    needs: precommit
    uses: ./.github/workflows/hopp_core_reusable.yml

  tauri-rust:
    needs: precommit
    uses: ./.github/workflows/tauri_rust_reusable.yml
